### ISSUE TITLE
Issues with Installing crystal 0.25.1

### ISSUE THREAD

**Issue by kolyaio** [pine/crenv#44] opened 2018-08-27 09:50 UTC
Hello, 

I'm trying to install crystal version 0.25.1 but I got weird error. 

```bash 
crenv install 0.25.1             ✔  2245  12:47:01
Resolving Crystal download URL by Remote Cache ... ok
Downloading Crystal binary tarball ...
https://homebrew.bintray.com/bottles/crystal-lang-0.25.1_1.high_sierra.bottle.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    33    0    33    0     0     64      0 --:--:-- --:--:-- --:--:--    64
Cannot read enough bytes from the tarfile at /Users/nikolai/.crenv/plugins/crystal-build/bin/../lib/CrystalBuild/Utils.pm line 44.
No files found for /Users/nikolai/.crenv/cache/0.25.1/crystal-lang-0.25.1_1.high_sierra.bottle.tar.gz at /Users/nikolai/.crenv/plugins/crystal-build/bin/../lib/CrystalBuild/Utils.pm line 45.
ok
Use of uninitialized value $extracted_dir in rename at /Users/nikolai/.crenv/plugins/crystal-build/bin/../lib/CrystalBuild/Installer/Crystal.pm line 91.
Moving the Crystal directory ...faild to move the Crystal directory No such file or directory
```

I'm using macOS on MBP 15 2017.
I successfully installed 0.25.0 or 0.26.0 but I need the 0.25.1 so it would work with amber. 

Using crenv 1.1.0-9-gf6f472f version 

If you need any more info please say :-)

**Comment by Sija** [comment] 2018-09-06 02:31
Duplicate of #43

**Comment by pine** [comment] 2020-01-23 06:10
Hi @kolyaio @Sija. I'm looking for maintainer.

Could you refer the issue if you have a free time? Thank you.

- #47

**Comment by taylorthurlow** [comment] 2022-10-10 19:04
Closing this as this is an issue with `crenv-build`. Please use [crystal-build-cr](https://github.com/crenv/crystal-build-cr) instead, and feel free to open an issue there if you continue to have problems.

**Closed as completed by taylorthurlow** 2022-10-10 19:04 UTC
