### ISSUE TITLE
Error when trying install 0.23.1

### ISSUE THREAD

**Issue by etroynov** [pine/crenv#36] opened 2017-08-31 16:53 UTC
I've been getting this error message when trying to install versions 0.19.2 or 0.19.4. Shards isn't building and I don't really know how to fix this.

Any help would be much appreciated!

Thanks in advance.
--
```
[root@ih663449 ~]# crenv install 0.23.1
Resolving Crystal download URL by Remote Cache ... ng
Resolving Crystal download URL by GitHub ... ng
Error: Version not found

[root@ih663449 ~]# 
```

**Comment by pine** [comment] 2017-09-01 07:23
Thanks reports! It may be bugs...

**Comment by airled** [comment] 2017-09-17 09:59
I have some issues with shards:
```
crenv install 0.23.1                                                                                           (master|✔)[12:53:46][air@air-pro]
Resolving Crystal download URL by Remote Cache ... ok
Downloading Crystal binary tarball ...
https://github.com/crystal-lang/crystal/releases/download/0.23.1/crystal-0.23.1-3-linux-x86_64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   625    0   625    0     0    733      0 --:--:-- --:--:-- --:--:--   733
100 18.9M  100 18.9M    0     0   937k      0  0:00:20  0:00:20 --:--:--  668k
ok
Moving the Crystal directory ...ok
Checking if Shards already exists ... ng
Resolving Shards download URL ... ok
Downloading Shards tarball ...
https://github.com/crystal-lang/shards/archive/v0.7.1.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   127    0   127    0     0    131      0 --:--:-- --:--:-- --:--:--   131
100 29722    0 29722    0     0  14787      0 --:--:--  0:00:02 --:--:-- 96814
ok
Building Shards ... crystal: /var/cache/omnibus/src/llvm/llvm-3.8.1.src/lib/CodeGen/LexicalScopes.cpp:160: llvm::LexicalScope* llvm::LexicalScopes::getOrCreateRegularScope(const llvm::DILocalScope*): Assertion `cast<DISubprogram>(Scope)->describes(MF->getFunction())' failed.
/home/air/.crenv/versions/0.23.1/bin/crystal: line 102:  7408 Aborted                 (core dumped) "$INSTALL_DIR/embedded/bin/crystal" "$@"

Retry building Shards ... crystal: /var/cache/omnibus/src/llvm/llvm-3.8.1.src/lib/CodeGen/LexicalScopes.cpp:160: llvm::LexicalScope* llvm::LexicalScopes::getOrCreateRegularScope(const llvm::DILocalScope*): Assertion `cast<DISubprogram>(Scope)->describes(MF->getFunction())' failed.
/home/air/.crenv/versions/0.23.1/bin/crystal: line 102:  7467 Aborted                 (core dumped) "$INSTALL_DIR/embedded/bin/crystal" "$@"
shards build faild: /home/air/.crenv/cache/0.23.1/shards-0.7.1 at /home/air/.crenv/plugins/crystal-build/bin/../lib/CrystalBuild/Builder/Shards.pm line 33, <DATA> line 2.
```

**Comment by ghost** [comment] 2018-01-24 17:47
Can reproduce it when trying to install crystal 0.24.1.

```
~ » crenv install 0.24.1
Resolving Crystal download URL by Remote Cache ... ng
Resolving Crystal download URL by GitHub ... ng
Error: Version not found
```

**Comment by pine** [comment] 2018-01-25 01:24
@etroynov @airled @yoru I'll fix this bug today. Sorry.

**Comment by etroynov** [comment] 2018-01-26 16:30
@pine good news :)

**Comment by klacointe** [comment] 2018-02-02 11:06
up ?

**Comment by taylorthurlow** [comment] 2022-10-10 19:05
Closing because this is an issue with `crystal-build`. Please use [crystal-build-cr](https://github.com/crenv/crystal-build-cr) and open an issue there if necessary.

**Closed as completed by taylorthurlow** 2022-10-10 19:05 UTC
Labels: bug
